name: build

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 19.8.1
      - name: Fetch dependencies
        run: npm ci
      - name: Run linters
        run: |
          npm run eslint
          npm run stylelint
      - name: Run tests
        run: npm run coverage
      - name: Bundle and build docker image
        run: docker build -t sw:latest .
